services:
  MySQL:
    image: mysql:latest
    container_name: MySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
  Admin:
    image: phpmyadmin
    container_name: Admin
    restart: always
    ports:
      - 6060:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=MySQL
volumes:
  database: