spring:
  application:
    name: backend
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://localhost:3306/ALMS
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 10MB

server:
  port: 8080

logging:
  level:
    com.example: INFO
    org.hibernate.SQL: INFO
    root: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: INFO