name: Build and Release Spring Boot App

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' 
          distribution: 'temurin'

      - name: Build the JAR file
        run: ./mvnw clean package -DskipTests

      - name: Get the version from pom.xml
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.version.outputs.version }}
          body: "Spring Boot App Release ${{ steps.version.outputs.version }}"
          draft: false
          prerelease: false

      - name: Upload JAR as a release asset
        if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/E-Library-${{ steps.version.outputs.version }}.jar
          asset_name: E-Library-${{ steps.version.outputs.version }}.jar
          asset_content_type: application/java-archive